version: '3.7'

services:
  app:
#    image: php:8.0.10-apache-buster
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: car-service-app
    environment:
      APP_ENV: dev
    volumes:
      - ./:/var/www/html:rw
    working_dir: /var/www/html
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      default:
      car-service:
        aliases: ['car-service-app']
  db:
    image: mysql:8.0
    container_name: car-service-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=car_service
      - MYSQL_USER=car_service
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_PASSWORD=abc123
    volumes:
      - ./docker/db/data:/var/lib/mysql
    networks:
      car-service:
        aliases: ["car-service-db"]

networks:
  car-service:
    name: car-service
